### ISSUE TITLE
The gate settings 

### ISSUE THREAD

**Issue by cvv2f** [Raffy27/OrionPanel#1]
Cant find that in the release copy

**Comment by Raffy27** [comment]
Default settings can be found in _Panel.exe.config_ which is included in the Release.
The default GateLocation is `https://localhost:1337/`, which is also the default listening interface for OrionServer. This setting may be changed from the GUI after logging in for the first time: **Side menu >> Configuration >> Gate Location --> Save settings**.

**Comment by cvv2f** [comment]
How to setup login access for this ? or is there anyway i can contact you ?

**Comment by Raffy27** [comment]
The default credentials are **admin** - **admin**. You can change these or add more by editing `OrionServer\Database\Users.xml` or by issuing the respective server command. Passwords are stored as unsalted SHA-256 hashes. This is out of scope for the issue.
raffy27@pm.me
